/**
 * You Want Services - Foundation Mock Data & Repository
 * Phase 1 Architecture
 */

import {
  ServiceRequest,
  Lead,
  Job,
  Payment,
  Message,
  Notification,
} from '../types/database';

export const INITIAL_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'req-101',
    publicRequestId: 'YS-2026-000101',
    customerId: 'demo-usr-customer-1',
    categoryId: 'cat-hvac',
    serviceSubcategoryId: 'sub-hvac-ac',
    title: 'Central AC blowing lukewarm air during heatwave',
    description: 'Upstairs heat pump unit stopped cooling yesterday. Needs diagnostic and refrigerant check.',
    urgency: 'WITHIN_24_HOURS',
    isUrgent: true,
    urgencyDetails: 'Temperature upstairs is reaching 88 degrees with elderly resident inside.',
    problemStarted: 'FEW_DAYS',
    address: '742 Evergreen Terrace',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62704',
    status: 'MATCHING',
    preferredDate: '2026-09-22',
    preferredTime: 'MORNING',
    flexibility: 'SOMEWHAT_FLEXIBLE',
    preferredScheduleDate: '2026-09-22',
    estimatedBudget: '$200 - $600',
    isDemo: true,
    createdAt: '2026-09-18T14:30:00Z',
    updatedAt: '2026-09-18T14:30:00Z',
    submittedAt: '2026-09-18T14:30:00Z',
    activities: [
      {
        id: 'act-101-1',
        serviceRequestId: 'req-101',
        activityType: 'REQUEST_SUBMITTED',
        description: 'Service request submitted by customer.',
        createdAt: '2026-09-18T14:30:00Z',
        createdBy: 'David Miller',
      },
    ],
  },
  {
    id: 'req-102',
    publicRequestId: 'YS-2026-000102',
    customerId: 'demo-usr-customer-1',
    categoryId: 'cat-plumbing',
    serviceSubcategoryId: 'sub-plumb-faucet',
    title: 'Main bathroom vanity faucet replacement',
    description: 'Purchased a new Kohler widespread faucet, need old corroded fixtures removed and new one installed.',
    urgency: 'THIS_WEEK',
    isUrgent: false,
    problemStarted: 'PAST_WEEK',
    address: '742 Evergreen Terrace',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62704',
    status: 'SUBMITTED',
    preferredDate: '2026-09-25',
    preferredTime: 'AFTERNOON',
    flexibility: 'FLEXIBLE',
    preferredScheduleDate: '2026-09-25',
    estimatedBudget: '$150 - $300',
    isDemo: true,
    createdAt: '2026-09-19T10:00:00Z',
    updatedAt: '2026-09-19T10:00:00Z',
    submittedAt: '2026-09-19T10:00:00Z',
    activities: [
      {
        id: 'act-102-1',
        serviceRequestId: 'req-102',
        activityType: 'REQUEST_SUBMITTED',
        description: 'Service request submitted by customer.',
        createdAt: '2026-09-19T10:00:00Z',
        createdBy: 'David Miller',
      },
    ],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-801',
    leadNumber: 'YL-2026-000801',
    serviceRequestId: 'req-101',
    customerId: 'demo-usr-customer-1',
    contractorId: 'demo-usr-contractor-1',
    serviceCategoryId: 'cat-hvac',
    categoryId: 'cat-hvac',
    city: 'Sacramento',
    state: 'CA',
    zipCode: '95814',
    projectDescription: 'AC blowing lukewarm air during peak heatwave afternoon.',
    urgency: 'WITHIN_24_HOURS',
    status: 'AVAILABLE',
    leadPrice: 20.00,
    isDemo: true,
    createdAt: '2026-09-18T14:35:00Z',
    updatedAt: '2026-09-18T14:35:00Z',
  },
  {
    id: 'lead-802',
    leadNumber: 'YL-2026-000802',
    serviceRequestId: 'req-103-demo',
    customerId: 'cust-demo-2',
    contractorId: 'demo-usr-contractor-1',
    serviceCategoryId: 'cat-hvac',
    categoryId: 'cat-hvac',
    city: 'Roseville',
    state: 'CA',
    zipCode: '95661',
    projectDescription: 'Commercial split HVAC inspection and seasonal filter replacement.',
    urgency: 'FLEXIBLE',
    status: 'ACCEPTED',
    leadPrice: 20.00,
    purchasedAt: '2026-09-17T09:15:00Z',
    isDemo: true,
    createdAt: '2026-09-17T08:00:00Z',
    updatedAt: '2026-09-17T09:15:00Z',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-501',
    serviceRequestId: 'req-103-demo',
    customerId: 'cust-demo-2',
    contractorId: 'demo-usr-contractor-1',
    leadId: 'lead-802',
    title: 'Furnace Pre-Winter Safety Inspection & Filter Replace',
    status: 'SCHEDULED',
    scheduledDate: '2026-09-23T10:00:00Z',
    agreedPrice: 185.00,
    notes: 'Access via side gate, gate code #4492',
    isDemo: true,
    createdAt: '2026-09-17T11:00:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    leadId: 'lead-802',
    payerId: 'demo-usr-contractor-1',
    amount: 35.00,
    type: 'LEAD_FEE',
    status: 'COMPLETED',
    isDemo: true,
    createdAt: '2026-09-17T09:15:00Z',
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-001',
    conversationId: 'conv-101',
    senderId: 'demo-usr-contractor-1',
    receiverId: 'demo-usr-customer-1',
    content: 'Hello David, this is Marcus with Apex HVAC. We saw your AC cooling request. Are you available for a diagnostic check between 10am and 12pm on Tuesday?',
    read: true,
    isDemo: true,
    createdAt: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'demo-usr-customer-1',
    title: 'Service Request Matching',
    message: 'Your AC diagnostic request is being matched with verified local HVAC contractors.',
    type: 'INFO',
    read: false,
    link: 'customer-my-requests',
    isDemo: true,
    createdAt: '2026-09-18T14:31:00Z',
  },
  {
    id: 'notif-002',
    userId: 'demo-usr-contractor-1',
    title: 'New HVAC Lead Nearby',
    message: 'New AC diagnostic request within 8 miles of your Springfield workshop.',
    type: 'SUCCESS',
    read: false,
    link: 'contractor-leads',
    isDemo: true,
    createdAt: '2026-09-18T14:35:00Z',
  },
];
